id: I8CC7F877
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-23T12:29:05+00:00'
last_modified: '2022-06-16T05:40:59.595758+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W16079
  title: རཱ་མ་ཎའི་རྟོགས་བརྗོད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0F4A:
      image_group_id: I1KG12348
      title: Volume 1 of rA ma Na'i rtogs brjod/
      total_pages: 206
      order: 1
      base_file: 0F4A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
